name: deploy

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main' 

jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # - name: Login to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
        # username: ${{ secrets.DOCKERHUB_USERNAME }}
        # password: ${{ secrets.DOCKERHUB_TOKEN }}

    # - name: Build and push
    #   uses: mr/build-push-action@v5
    #   with:
    #     push: true
    #     repository: ${{ github.repository }}
    #     tag_with_ref: true
    #     tag_with_sha: true
    #     tags: ${{ github.sha }}
    - name: Build and push
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        # repository: ${{ github.repository }}
        image: 741586369/portfolio-web
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD}}